### ISSUE TITLE
(Exception ticking world) Crashes server when playing with ValhallaMMO addon ValhallaRaces. No problem when only one is running.

### ISSUE THREAD

**Issue by StormShaddy** [nulli0n/nightcore-spigot#10]
Happens when more then 1 people present on the server, after some undefined amount of time, usually 5 mins

Log in files
[message (1).txt](https://github.com/user-attachments/files/16021729/message.1.txt)

**Comment by StormShaddy** [comment]
Exception ticking world

**Comment by nulli0n** [comment]
Chunk unloading is broken in 1.21
https://hub.spigotmc.org/jira/browse/SPIGOT-7780
https://hub.spigotmc.org/jira/browse/SPIGOT-7759
Nothing I can do currently. Disable Track_Player_Blocks in the jobs/challenges plugin config(s).
