### ISSUE TITLE
(Could not pass event ChunkUnloadEvent to nightcore v2.6.2) Crashes server when playing with ValhallaMMO addon ValhallaRaces. No problem when only one is running.

### ISSUE THREAD

**Issue by StormShaddy** [nulli0n/nightcore-spigot#11]
Same as "Exception ticking world" - Happens when more then 1 people present on the server, after some undefined amount of time, usually 5 mins
Log in files
[message.txt](https://github.com/user-attachments/files/16021772/message.txt)

**Comment by nulli0n** [comment]
Chunk unloading is broken in 1.21
https://hub.spigotmc.org/jira/browse/SPIGOT-7780
https://hub.spigotmc.org/jira/browse/SPIGOT-7759
Nothing I can do currently. Disable Track_Player_Blocks in the jobs/challenges plugin config(s).

**Comment by nulli0n** [comment]
Should be fixed in latest spigot/paper builds.

**Comment by jk33v3rs** [comment]
just came to report this issue (different 2 plugins, I suspect mine was EliteMobs) and saw there was a new version - will download and install now and report back on if I can trigger the issue again. 1.21/nightcore 2.6.2
