### ISSUE TITLE
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.

### ISSUE THREAD

**Issue by JorisvD01** [nulli0n/nightcore-spigot#15]
![image](https://github.com/user-attachments/assets/98551193-bfad-4d2b-9607-b0697139ac8f)

Hello. After updating to the newest version of ExcellentChallenges, ExcellentCrates and Nightcore yesterday we are facing this issue where this message keeps popping up, and prevening users from playing on the server.

We are using Paper version git-Paper-399 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: b03f255)

Plugin versions; 
- Nightcore: 2.6.3
- ExcellentChallenges 3.1.3
- ExcellentCrates 5.3.1

This issue only started appearing after we upgraded to the most recent versions of these plugins. We are using 7 servers all running these plugins, connected to 1 MySQL database

**Comment by nulli0n** [comment]
Solution sent in discord.
