### ISSUE TITLE
TROJAN DETECTED BY WINDOWS DEFENDER IN NEWEST VERSION

### ISSUE THREAD

**Issue by rawtalnt** [nulli0n/nightcore-spigot#2]
hi, im here at the need of having nightcore to run ExcellentEnchants. Windows defender instantaneously marks nightcore to have brought some "Trojan:Wacatac" file 

I do not feel safe downloading this. Has it been compromised?

**Comment by nulli0n** [comment]
If you don't trust open source projects, then I have no idea what would be safe for you. Don't use it and switch to other plugin.
