### ISSUE TITLE
nightcore 2.6.2 Crash

### ISSUE THREAD

**Issue by R00tB33rMan** [nulli0n/nightcore-spigot#8]
Prior to nightcore 2.6.2, I've encountered no issues. Here's the crash log: https://mclo.gs/NTLEe3R

Heavy thread creation: https://spark.lucko.me/yuC55RsOga

**Comment by nulli0n** [comment]
[nightcore-2.6.2.jar.zip](https://github.com/user-attachments/files/15877510/nightcore-2.6.2.jar.zip)
Could you try this version please?

**Comment by R00tB33rMan** [comment]
> [nightcore-2.6.2.jar.zip](https://github.com/user-attachments/files/15877510/nightcore-2.6.2.jar.zip) Could you try this version please?

Will do

**Comment by R00tB33rMan** [comment]
No crashes thus far with 6 hours of uptime.

**Comment by nulli0n** [comment]
Could you please share spark profile for this?

**Comment by R00tB33rMan** [comment]
> Could you please share spark profile for this?

https://spark.lucko.me/d8paSkXLBE

**Comment by nulli0n** [comment]
Thanks! I will keep this open for a while. I updated the latest release with a more optimized version if you would like to try it out.
